version: 2

updates:
  # ---- GitHub Actions ----
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - stacksjb
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      gha-all:
        patterns: ["*"]                 # include all actions
        update-types: ["major","minor","patch"]  # = all updates
